/**
 * A curated list of popular Google Font family names.
 *
 * The `useFont` and `fetchFont` functions work with any Google Font name —
 * this catalog is provided for discoverability and font picker UIs.
 *
 * ```ts
 * import { fontCatalog } from '@rendiv/google-fonts';
 * // fontCatalog = ['ABeeZee', 'Abel', 'Abril Fatface', ...]
 * ```
 */
export const fontCatalog: readonly string[] = [
  'ABeeZee',
  'Abel',
  'Abril Fatface',
  'Alegreya',
  'Alegreya Sans',
  'Alfa Slab One',
  'Anton',
  'Archivo',
  'Archivo Narrow',
  'Arimo',
  'Assistant',
  'Barlow',
  'Barlow Condensed',
  'Bebas Neue',
  'Bitter',
  'Cairo',
  'Cabin',
  'Catamaran',
  'Chakra Petch',
  'Comfortaa',
  'Cormorant Garamond',
  'Crimson Text',
  'DM Sans',
  'DM Serif Display',
  'Dosis',
  'EB Garamond',
  'Exo 2',
  'Fira Code',
  'Fira Sans',
  'Fjalla One',
  'Fredoka One',
  'Heebo',
  'Hind',
  'IBM Plex Mono',
  'IBM Plex Sans',
  'Inconsolata',
  'Inter',
  'Josefin Sans',
  'Kanit',
  'Karla',
  'Lato',
  'Lexend',
  'Libre Baskerville',
  'Libre Franklin',
  'Lobster',
  'Lora',
  'Manrope',
  'Maven Pro',
  'Merriweather',
  'Merriweather Sans',
  'Montserrat',
  'Mukta',
  'Mulish',
  'Noto Sans',
  'Noto Sans JP',
  'Noto Sans KR',
  'Noto Sans SC',
  'Noto Sans TC',
  'Noto Serif',
  'Nunito',
  'Nunito Sans',
  'Open Sans',
  'Oswald',
  'Outfit',
  'Overpass',
  'Oxygen',
  'PT Sans',
  'PT Serif',
  'Pacifico',
  'Poppins',
  'Prompt',
  'Public Sans',
  'Quicksand',
  'Rajdhani',
  'Raleway',
  'Red Hat Display',
  'Righteous',
  'Roboto',
  'Roboto Condensed',
  'Roboto Flex',
  'Roboto Mono',
  'Roboto Slab',
  'Rubik',
  'Russo One',
  'Saira',
  'Signika',
  'Slabo 27px',
  'Source Code Pro',
  'Source Sans 3',
  'Source Serif 4',
  'Space Grotesk',
  'Space Mono',
  'Spectral',
  'Teko',
  'Titillium Web',
  'Ubuntu',
  'Ubuntu Mono',
  'Urbanist',
  'Varela Round',
  'Work Sans',
  'Yanone Kaffeesatz',
  'Zilla Slab',
];
